api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register("favorites", views.FavoriteViewSet, basename="favorites")
router.register("subscriptions", views.FollowViewSet, basename="subscriptions")
router.register("purchases", views.ShopListViewSet, basename="purchases")
router.register("ingredients", views.IngredientViewSet, basename="ingredients")

urlpatterns = [
    path("", include(router.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa


urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("simplepages.urls", namespace="about")),
    path("admincontrol/", admin.site.urls),
    path("", include("recipes.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

simplepages/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе</a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/includes/mainheader.html
<div class="main__header">
    <h1 class="main__title">{% if profile %}
                            {% firstof profile.get_full_name profile.username %}
                            {% endif %}
                            {{ header_title }}
    </h1>
    {% if need_tags %}
        <form method="get" id="tag_form_id" onchange="document.getElementById('tag_form_id').submit()">
            <ul class="tags">
                {% include "recipes/includes/tagform.html" with taglist=form.tags %}
            </ul>
        </form>
    {% endif %}
</div>

templates/includes/nav.html
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__items list">
            {% with resolver=request.resolver_match basket_size=user.shoplists.count %}
            <li class="nav__item {% if resolver.url_name == 'index' %}nav__item_active{% endif %}
            {% if 'auth/' in resolver.route and 'password_change' not in resolver.route %}nav__item_disabled{% endif %}">
                <a href="{% url 'index' %}" class="nav__link link">Рецепты</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav__item {% if resolver.url_name == 'follows' %}nav__item_active{% endif %}">
                <a href="{% url 'follows' %}" class="nav__link link">Мои подписки</a>
            </li>
            <li class="nav__item {% if resolver.url_name == 'new_recipe' %}nav__item_active{% endif %}">
                <a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a>
            </li>
            <li class="nav__item {% if resolver.url_name == 'favorites' %}nav__item_active{% endif %}">
                <a href="{% url 'favorites' %}" class="nav__link link">Избранное</a>
            </li>
            <li class="nav__item {% if resolver.url_name == 'shoplist' %}nav__item_active{% endif %}
            {% if 'auth/' in resolver.route and 'password_change' not in resolver.route %}nav__item_disabled{% endif %}">
                <a href="{% url 'shoplist' %}" class="nav__link link">Список покупок</a>
                {% if basket_size == 0 %}
                    <span hidden class="badge badge_style_blue nav__badge" id="counter">{{ basket_size }}</span>
                {% else %}
                    <span class="badge badge_style_blue nav__badge" id="counter">{{ basket_size }}</span>
                {% endif %}
            </li>
            {% endif %}
        </ul>
        <ul class="nav__items list">
            {% if user.is_authenticated %}
            <li class="nav__item {% if user.username == resolver.kwargs.username %}nav__item_active{% endif %}">
                <a href="{% url 'profile' username=user.username %}" class="nav__link link">{{ user.username }}</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'logout' %}" class="nav__link link">Выход</a>
            </li>
            {% else %}
            <li class="nav__item">
                <a href="{% url 'login' %}" class="nav__link link">Войти</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'signup' %}"><button class="button button_style_blue">Создать аккаунт</button></a>
            </li>
            {% endif %}
            {% endwith %}
        </ul>
    </div>
</nav>

templates/includes/paginator.html
{% load recipe_filters %}
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
        <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=items.previous_page_number %}"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if items.number == i %}
            <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="?{% url_replace page=i %}">{{ i }}</a></li>
            {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if items.has_next %}
        <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=items.next_page_number %}"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>